### ISSUE TITLE
Will Elli APIs support .net core 3.1 applications

### ISSUE THREAD

**Issue by athulacananth** [EllieMae/developerconnect-dotnet-bindings#26]
Recently i am working on .net core 3.1 web applications, what changes will be need to work with elli API on .net core platforms ?

```
       ```
[HttpGet]
        public Object Get()
        {
            ApiConfiguration config = (ApiConfiguration)ConfigurationManager.GetSection("ElliApiConfig");

            //Passwords and other sensitive information should be handled by consumer application suitably            
            string instanceId = "BEXXXXX", userName = "XXXX", password = "XXXXX!";

            var credentials = new UserCredential
            {
                IdentityType = IdentityType.Lender,
                InstanceId = instanceId,
                Password = password,
                UserName = userName
            };

           return  _accessToken = AccessToken.GetAccessToken(credentials);

        }
```
```
it is simple api call to get the access token ! This is throwing error **System.NullReferenceException: 'Object reference not set to an instance of an object.'**

**Comment by TylerBrinkley** [comment]
The Ellie Mae .NET Bindings target .NET Framework 4.5 and utilize the App.config/Web.config file and as such is not supported in .NET Core. If you wish to access the Developer Connect API's from .NET Core I'd suggest you consider using a different library such as [EncompassRest](https://github.com/EncompassRest/EncompassRest) which targets .NET Standard as well as .NET Framework or else make the calls directly with an `HttpClient` instance.

**Comment by athulacananth** [comment]
@TylerBrinkley  any sample codes are available ? for API applications ?
