### ISSUE TITLE
Efolder Api GetAttachments returns a void not a List of Attachments

### ISSUE THREAD

**Issue by aleeVicFin** [EllieMae/developerconnect-dotnet-bindings#6]
Is there a reason why getAttachments is returning a void and not a list of Attachements? How are we supposed to get the list?

**Comment by Ellie-cpawar** [comment]
@aleeVicFin Sorry for the inconvenience. We are aware of the issues and updated package with the fix for this and #3 issue will be addressed in nextrelease.

**Comment by jvidaurrazaga** [comment]
Do you have an ETA on the next release? I’m sure this could be a quick fix and get us all going.

**Comment by Ellie-cpawar** [comment]
@jvidaurrazaga , @aleeVicFin 
New packages are released to addresse this issue.

**Comment by aleeVicFin** [comment]
Excellent. TYVM
