### ISSUE TITLE
Get loan returning datetime error?

### ISSUE THREAD

**Issue by aleeVicFin** [EllieMae/developerconnect-dotnet-bindings#8]
{"Error calling GetLoan: {\"summary\":\"Bad Request\",\"details\":\"The supplied DateTime represents an invalid time.  For example, when the clock is adjusted forward, any time in the period that is skipped is invalid.\\u000d\\u000aParameter name: dateTime\",\"errorCode\":\"EBS-912\"}"}	Elli.Api.Loans.Client.ApiException

I'm just using loanApiClient.GetLoan(loanGUID); Only seems to happen occasionally.

**Comment by Ellie-cpawar** [comment]
@aleeVicFin We have fixed this issue and it will be release in next month SP.
